/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { APrivatezPausable } from "./APrivatezPausable";
export type { IPrivatezPausable } from "./IPrivatezPausable";
export type { PrivatezPausable } from "./PrivatezPausable";
