/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenShop } from "./ERC1155TokenShop";
export type { IERC1155TokenShop } from "./IERC1155TokenShop";
