/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iGovernorSol from "./IGovernor.sol";
export type { iGovernorSol };
export type { Governor } from "./Governor";
