/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155TokenShop__factory } from "./ERC1155TokenShop__factory";
export { IERC1155TokenShop__factory } from "./IERC1155TokenShop__factory";
