/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export * as zErc1155TokenShop from "./zERC1155TokenShop";
export { ERC1155TokenShop__factory } from "./ERC1155TokenShop__factory";
export { IERC1155TokenShop__factory } from "./IERC1155TokenShop__factory";
