/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC1155TokenShop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155TokenShop__factory>;
    getContractFactory(
      name: "IERC1155TokenShop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155TokenShop__factory>;
    getContractFactory(
      name: "APrivatezPausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.APrivatezPausable__factory>;
    getContractFactory(
      name: "IzPausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IzPausable__factory>;
    getContractFactory(
      name: "ZPausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZPausable__factory>;
    getContractFactory(
      name: "IPrivatezPausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPrivatezPausable__factory>;
    getContractFactory(
      name: "PrivatezPausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivatezPausable__factory>;
    getContractFactory(
      name: "ERC1155Struct",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Struct__factory>;
    getContractFactory(
      name: "ERC1155Master",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Master__factory>;
    getContractFactory(
      name: "ERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC1155Snapshot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Snapshot__factory>;
    getContractFactory(
      name: "Membership",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Membership__factory>;
    getContractFactory(
      name: "ProvaMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProvaMaster__factory>;
    getContractFactory(
      name: "USDC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.USDC__factory>;
    getContractFactory(
      name: "ZionLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZionLib__factory>;
    getContractFactory(
      name: "ERC1155IndividualURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155IndividualURI__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "ERC1155Lib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Lib__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "ERC20Lib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Lib__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;

    getContractAt(
      name: "ERC1155TokenShop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155TokenShop>;
    getContractAt(
      name: "IERC1155TokenShop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155TokenShop>;
    getContractAt(
      name: "APrivatezPausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.APrivatezPausable>;
    getContractAt(
      name: "IzPausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IzPausable>;
    getContractAt(
      name: "ZPausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZPausable>;
    getContractAt(
      name: "IPrivatezPausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPrivatezPausable>;
    getContractAt(
      name: "PrivatezPausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivatezPausable>;
    getContractAt(
      name: "ERC1155Struct",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Struct>;
    getContractAt(
      name: "ERC1155Master",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Master>;
    getContractAt(
      name: "ERC1155Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Receiver>;
    getContractAt(
      name: "ERC1155Snapshot",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Snapshot>;
    getContractAt(
      name: "Membership",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Membership>;
    getContractAt(
      name: "ProvaMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ProvaMaster>;
    getContractAt(
      name: "USDC",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.USDC>;
    getContractAt(
      name: "ZionLib",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZionLib>;
    getContractAt(
      name: "ERC1155IndividualURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155IndividualURI>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "ERC1155Lib",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Lib>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "ERC20Lib",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Lib>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
